@startuml
actor Usuario

participant RegistroController
participant UsuarioDAO
participant ConexionBD
database MySQL

Usuario -> RegistroController : completarFormulario()
RegistroController -> UsuarioDAO : registrarUsuario(usuario)

UsuarioDAO -> ConexionBD : getConnection()
ConexionBD --> UsuarioDAO : Connection

UsuarioDAO -> MySQL : INSERT INTO usuarios
MySQL --> UsuarioDAO : confirmación

UsuarioDAO --> RegistroController : true
RegistroController --> Usuario : mostrarMensajeExito()

@enduml